# Generated by Django 4.0.1 on 2022-01-11 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 1, 11, 17, 59, 2, 930567))),
            ],
        ),
    ]
